# Generated by Django 2.1.10 on 2019-07-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRO', 'Proposed'), ('INT', 'Intake'), ('FOS', 'Fostered'), ('ADO', 'Adopted')], max_length=3)),
                ('propose_date', models.DateField()),
                ('intake_date', models.DateField()),
                ('intake_source', models.CharField(max_length=30)),
                ('finished_quarantine_date', models.DateField()),
                ('cat_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=30)),
                ('cat_photo', models.ImageField(null=True, upload_to='photos')),
                ('cat_medical_history', models.FileField(null=True, upload_to='pdfs')),
                ('notes', models.CharField(max_length=100)),
                ('mh_attached', models.BooleanField()),
                ('spayed_neutered', models.BooleanField()),
                ('fvrcp_vaccination', models.BooleanField()),
                ('rabies_vaccination', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FosterHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('contact_info', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('home_environment', models.CharField(max_length=50)),
                ('car_ownership', models.BooleanField()),
                ('freestyle_notes', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
