# Generated by Django 2.1.10 on 2019-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20190707_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_medical_history',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
