# Generated by Django 2.1.10 on 2019-07-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20190707_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='notes',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='spayed_neutered',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='email',
            field=models.CharField(default='Test@gmail.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='type',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosterhome',
            name='car_ownership',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosterhome',
            name='contact_info',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosterhome',
            name='freestyle_notes',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosterhome',
            name='home_environment',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosterhome',
            name='status',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intakesource',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
